#include <nds.h>
#include <stdio.h>
#include <stdbool.h>

#define W 256
#define H 192
#define TILE 16
#define MW 16
#define MH 11
#define INV_MAX 12

enum { GRASS, WATER, SOIL, TREE, ROCK, PATH, HOUSE, SHOP };
enum { EMPTY, SEED, GROWING, READY };

static u16 *fb;
static int px=7, py=8, energy=100, day=1, money=80;
static int seeds=8, selected=0, area=0, menu=0, message_timer=0;
static u8 crop[MH][MW], wet[MH][MW];

static const u8 farm[MH][MW]={
{WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER},
{WATER,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,WATER},
{WATER,GRASS,TREE,GRASS,GRASS,GRASS,GRASS,SOIL,SOIL,GRASS,GRASS,ROCK,GRASS,GRASS,GRASS,WATER},
{WATER,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,SOIL,SOIL,GRASS,GRASS,GRASS,GRASS,TREE,GRASS,WATER},
{WATER,GRASS,GRASS,ROCK,GRASS,GRASS,GRASS,SOIL,SOIL,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,WATER},
{WATER,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,ROCK,GRASS,GRASS,WATER},
{WATER,GRASS,GRASS,GRASS,TREE,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,WATER},
{WATER,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,TREE,GRASS,WATER},
{WATER,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,WATER},
{WATER,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,GRASS,WATER},
{WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER,WATER}
};
